### PR TITLE
Update syntax for Swift 3/iOS 10

### PR DESCRIPTION
**Pull request by kevinwo**
Re: issue #1, this pull request provides preliminary support for Swift 3 and iOS 10.  I've update syntax wherever there were warning and errors on build, and I've tested as far as the iOS example application, which seems to work.  tvOS simulator seems to be a bit wonky in Beta 1, so was unable to test there.

Unit tests will not run currently as there is a complaint on compile about an invalid path.  I haven't looked at this yet, but expect the library should hopefully work.

### CODE REVIEW

**Comment by kevinwo** [comment]
Apologies, I see I set up the merge to occur on develop.  If a separate branch is created, I can re-submit the request.

**Comment by mathiasnagler** [comment]
Thanks a lot for the PR! 👍 

I will set up a new branch `swift-3.0` so we can keep the changes on a separate branch for now. It would be great if you would resubmit the request, I will check it out then.

**Comment by mathiasnagler** [comment]
@kevinwo I just created the branch `swift-3.0`.

**Comment by kevinwo** [comment]
Sweet, thanks!  Just submitted another pull request.

**Pull request closed without merging**
